### ISSUE TITLE
Notification failed

### ISSUE THREAD

**Issue by ajevanNad** [niroigen/ELEC390Application#4]
Notification did not work as expected. Reminder was set by choosing current room about 3hrs earlier and reminder did not go off.

**Comment by niroigen** [comment]
Changed the code, so just verify by tomorrow

**Comment by aboodca** [comment]
hello guys, just want to ask a few questions, let's say I open the app and I went to Room 807, how can the app know if the user in Room 807? this feature should be applied when the navigation part is done? or if we allow the user to input his/her location (which room the user is in)?

**Comment by niroigen** [comment]
Currently the user has to say which room they are in which is done by clicking the button in the LabDetail activity, but this is just until the navigation part is implemented so we can use the users location
