### ISSUE TITLE
add fail message when internet connection weak or not connected to the internet

### ISSUE THREAD

**Issue by ajevanNad** [niroigen/ELEC390Application#5]
add message to let the user know that device is not connected to the internet. since instead it outputs a blank page and says that it is done.

**Comment by niroigen** [comment]
Not able to deal with when internet connection is lost during the initialization

**Comment by ajevanNad** [comment]
tried, i think i ended up with same thing as what you did, only able to check if internet connection exists at beginning. Looks like have to use something called broadcast receiver.

**Comment by ajevanNad** [comment]
just change the code back if you want
