### ISSUE TITLE
app crashes on start up

### ISSUE THREAD

**Issue by ajevanNad** [niroigen/ELEC390Application#7]
Seems like its due to applicationsStored being null?
Fails at line 129 in GetRoomInfoAsync.java in the for loop

**Comment by niroigen** [comment]
Ohh okay my work around for that I would say is comment out the statement where it checks whether it is null like the two variables, 

Ex (if(is connected))

And let the application run, then you can put condition back and it should be fine

**Comment by niroigen** [comment]
Fixed the issue and fixed
