### ISSUE TITLE
Not able to refresh 

### ISSUE THREAD

**Issue by ajevanNad** [niroigen/ELEC390Application#8]
class in room 854 @ 1600, at 1604 not able to refresh to see 854 move to the red section, instead it stays in yellow section.
Had to close the app and open it again to see the change

**Comment by ajevanNad** [comment]
Also, once the class is done, room should be free but instead goes into yellow section and says next class @1400, but the current time is 1730.
*tried refreshing, didn't update
*tried closing and restarting the app, didn't update

**Comment by niroigen** [comment]
Bug fixed on commit, verify if it's good

**Comment by niroigen** [comment]
Just checked and it seems to still be a problem with the refreshing so I will look into this more

**Comment by aboodca** [comment]
we are working on this issue

**Comment by niroigen** [comment]
Just tried it out and at 8:59 to 9 it did not refresh, will have to look into this again

**Comment by niroigen** [comment]
Should be fixed now, just verify

**Comment by niroigen** [comment]
Fixed on last commit
